apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: plaulkar/flask-ip-logger:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-db-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-db-config
              key: db-name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: flask-db-config
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
